### ISSUE TITLE
[Feature Request] REI Support

### ISSUE THREAD

**Issue by EvanHsieh0415** [Swedz/Mana-Visualizer#3]
btw I'm curious why you chose EMI as your preferred option.

**Comment by Swedz** [comment]
I can look into adding REI support. I chose EMI because EMI is all around better made and has a few extra features I'm a huge fan of (recipe trees, preferred recipes, for example). I also like the dev for EMI a lot better, not that I have anything against any of the REI devs, just that EMI is super kind and helpful :P

**Comment by Swedz** [comment]
Added in 113379d. Should be on modrinth as version 1.1+1.19.2 soon

**Comment by EvanHsieh0415** [comment]
thx
